Search.appendIndex(
    [
                {
            "fqsen": "\\Core\\BaseController",
            "name": "BaseController",
            "summary": "",
            "url": "classes/Core-BaseController.html"
        },                {
            "fqsen": "\\Core\\BaseController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Core-BaseController.html#method___construct"
        },                {
            "fqsen": "\\Core\\BaseController\u003A\u003Abefore\u0028\u0029",
            "name": "before",
            "summary": "",
            "url": "classes/Core-BaseController.html#method_before"
        },                {
            "fqsen": "\\Core\\BaseController\u003A\u003Aafter\u0028\u0029",
            "name": "after",
            "summary": "",
            "url": "classes/Core-BaseController.html#method_after"
        },                {
            "fqsen": "\\Core\\BaseController\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "",
            "url": "classes/Core-BaseController.html#method_render"
        },                {
            "fqsen": "\\Core\\BaseController\u003A\u003Aredirect\u0028\u0029",
            "name": "redirect",
            "summary": "",
            "url": "classes/Core-BaseController.html#method_redirect"
        },                {
            "fqsen": "\\Core\\BaseController\u003A\u003Ajson\u0028\u0029",
            "name": "json",
            "summary": "",
            "url": "classes/Core-BaseController.html#method_json"
        },                {
            "fqsen": "\\Core\\BaseController\u003A\u003A\u0024routeParams",
            "name": "routeParams",
            "summary": "",
            "url": "classes/Core-BaseController.html#property_routeParams"
        },                {
            "fqsen": "\\Core\\BaseController\u003A\u003A\u0024response",
            "name": "response",
            "summary": "",
            "url": "classes/Core-BaseController.html#property_response"
        },                {
            "fqsen": "\\Core\\BaseController\u003A\u003A\u0024view",
            "name": "view",
            "summary": "",
            "url": "classes/Core-BaseController.html#property_view"
        },                {
            "fqsen": "\\Core\\DAO",
            "name": "DAO",
            "summary": "",
            "url": "classes/Core-DAO.html"
        },                {
            "fqsen": "\\Core\\DAO\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Core-DAO.html#method___construct"
        },                {
            "fqsen": "\\Core\\DAO\u003A\u003Aget_some\u0028\u0029",
            "name": "get_some",
            "summary": "",
            "url": "classes/Core-DAO.html#method_get_some"
        },                {
            "fqsen": "\\Core\\DAO\u003A\u003Aget_all\u0028\u0029",
            "name": "get_all",
            "summary": "",
            "url": "classes/Core-DAO.html#method_get_all"
        },                {
            "fqsen": "\\Core\\DAO\u003A\u003Afind\u0028\u0029",
            "name": "find",
            "summary": "",
            "url": "classes/Core-DAO.html#method_find"
        },                {
            "fqsen": "\\Core\\DAO\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "",
            "url": "classes/Core-DAO.html#method_register"
        },                {
            "fqsen": "\\Core\\DAO\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/Core-DAO.html#method_update"
        },                {
            "fqsen": "\\Core\\DAO\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/Core-DAO.html#method_delete"
        },                {
            "fqsen": "\\Core\\DAO\u003A\u003AcascadeDelete\u0028\u0029",
            "name": "cascadeDelete",
            "summary": "",
            "url": "classes/Core-DAO.html#method_cascadeDelete"
        },                {
            "fqsen": "\\Core\\DAO\u003A\u003AgetRelations\u0028\u0029",
            "name": "getRelations",
            "summary": "",
            "url": "classes/Core-DAO.html#method_getRelations"
        },                {
            "fqsen": "\\Core\\DAO\u003A\u003AdeleteAll\u0028\u0029",
            "name": "deleteAll",
            "summary": "",
            "url": "classes/Core-DAO.html#method_deleteAll"
        },                {
            "fqsen": "\\Core\\DAO\u003A\u003A\u0024connection",
            "name": "connection",
            "summary": "",
            "url": "classes/Core-DAO.html#property_connection"
        },                {
            "fqsen": "\\Core\\DAO\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/Core-DAO.html#property_table"
        },                {
            "fqsen": "\\Core\\DAO\u003A\u003A\u0024Relations",
            "name": "Relations",
            "summary": "",
            "url": "classes/Core-DAO.html#property_Relations"
        },                {
            "fqsen": "\\Core\\Database",
            "name": "Database",
            "summary": "",
            "url": "classes/Core-Database.html"
        },                {
            "fqsen": "\\Core\\Database\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Core-Database.html#method___construct"
        },                {
            "fqsen": "\\Core\\Database\u003A\u003AgetInstance\u0028\u0029",
            "name": "getInstance",
            "summary": "",
            "url": "classes/Core-Database.html#method_getInstance"
        },                {
            "fqsen": "\\Core\\Database\u003A\u003Aquery\u0028\u0029",
            "name": "query",
            "summary": "",
            "url": "classes/Core-Database.html#method_query"
        },                {
            "fqsen": "\\Core\\Database\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Core-Database.html#method_get"
        },                {
            "fqsen": "\\Core\\Database\u003A\u003Afind\u0028\u0029",
            "name": "find",
            "summary": "",
            "url": "classes/Core-Database.html#method_find"
        },                {
            "fqsen": "\\Core\\Database\u003A\u003AfindOrFail\u0028\u0029",
            "name": "findOrFail",
            "summary": "",
            "url": "classes/Core-Database.html#method_findOrFail"
        },                {
            "fqsen": "\\Core\\Database\u003A\u003AcascadeDelete\u0028\u0029",
            "name": "cascadeDelete",
            "summary": "",
            "url": "classes/Core-Database.html#method_cascadeDelete"
        },                {
            "fqsen": "\\Core\\Database\u003A\u003ADelete\u0028\u0029",
            "name": "Delete",
            "summary": "",
            "url": "classes/Core-Database.html#method_Delete"
        },                {
            "fqsen": "\\Core\\Database\u003A\u003ADeleteAll\u0028\u0029",
            "name": "DeleteAll",
            "summary": "",
            "url": "classes/Core-Database.html#method_DeleteAll"
        },                {
            "fqsen": "\\Core\\Database\u003A\u003ADeleteAllHard\u0028\u0029",
            "name": "DeleteAllHard",
            "summary": "",
            "url": "classes/Core-Database.html#method_DeleteAllHard"
        },                {
            "fqsen": "\\Core\\Database\u003A\u003AJoinFilter\u0028\u0029",
            "name": "JoinFilter",
            "summary": "",
            "url": "classes/Core-Database.html#method_JoinFilter"
        },                {
            "fqsen": "\\Core\\Database\u003A\u003A\u0024instance",
            "name": "instance",
            "summary": "",
            "url": "classes/Core-Database.html#property_instance"
        },                {
            "fqsen": "\\Core\\Database\u003A\u003A\u0024connection",
            "name": "connection",
            "summary": "",
            "url": "classes/Core-Database.html#property_connection"
        },                {
            "fqsen": "\\Core\\Database\u003A\u003A\u0024statement",
            "name": "statement",
            "summary": "",
            "url": "classes/Core-Database.html#property_statement"
        },                {
            "fqsen": "\\Core\\Request",
            "name": "Request",
            "summary": "",
            "url": "classes/Core-Request.html"
        },                {
            "fqsen": "\\Core\\Request\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Core-Request.html#method___construct"
        },                {
            "fqsen": "\\Core\\Request\u003A\u003AgetUrl\u0028\u0029",
            "name": "getUrl",
            "summary": "",
            "url": "classes/Core-Request.html#method_getUrl"
        },                {
            "fqsen": "\\Core\\Request\u003A\u003A\u0024url",
            "name": "url",
            "summary": "",
            "url": "classes/Core-Request.html#property_url"
        },                {
            "fqsen": "\\Core\\Response",
            "name": "Response",
            "summary": "",
            "url": "classes/Core-Response.html"
        },                {
            "fqsen": "\\Core\\Response\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Core-Response.html#method___construct"
        },                {
            "fqsen": "\\Core\\Response\u003A\u003Aredirect\u0028\u0029",
            "name": "redirect",
            "summary": "",
            "url": "classes/Core-Response.html#method_redirect"
        },                {
            "fqsen": "\\Core\\Response\u003A\u003Aabort\u0028\u0029",
            "name": "abort",
            "summary": "",
            "url": "classes/Core-Response.html#method_abort"
        },                {
            "fqsen": "\\Core\\Response\u003A\u003A\u0024view",
            "name": "view",
            "summary": "",
            "url": "classes/Core-Response.html#property_view"
        },                {
            "fqsen": "\\Core\\Router",
            "name": "Router",
            "summary": "",
            "url": "classes/Core-Router.html"
        },                {
            "fqsen": "\\Core\\Router\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Core-Router.html#method___construct"
        },                {
            "fqsen": "\\Core\\Router\u003A\u003AaddRoute\u0028\u0029",
            "name": "addRoute",
            "summary": "",
            "url": "classes/Core-Router.html#method_addRoute"
        },                {
            "fqsen": "\\Core\\Router\u003A\u003AgetRoutes\u0028\u0029",
            "name": "getRoutes",
            "summary": "",
            "url": "classes/Core-Router.html#method_getRoutes"
        },                {
            "fqsen": "\\Core\\Router\u003A\u003AmatchRoute\u0028\u0029",
            "name": "matchRoute",
            "summary": "",
            "url": "classes/Core-Router.html#method_matchRoute"
        },                {
            "fqsen": "\\Core\\Router\u003A\u003AgetParams\u0028\u0029",
            "name": "getParams",
            "summary": "",
            "url": "classes/Core-Router.html#method_getParams"
        },                {
            "fqsen": "\\Core\\Router\u003A\u003Adispatch\u0028\u0029",
            "name": "dispatch",
            "summary": "",
            "url": "classes/Core-Router.html#method_dispatch"
        },                {
            "fqsen": "\\Core\\Router\u003A\u003AremoveQueryStringVariables\u0028\u0029",
            "name": "removeQueryStringVariables",
            "summary": "",
            "url": "classes/Core-Router.html#method_removeQueryStringVariables"
        },                {
            "fqsen": "\\Core\\Router\u003A\u003AtoStudlyCaps\u0028\u0029",
            "name": "toStudlyCaps",
            "summary": "",
            "url": "classes/Core-Router.html#method_toStudlyCaps"
        },                {
            "fqsen": "\\Core\\Router\u003A\u003AtoCamelCase\u0028\u0029",
            "name": "toCamelCase",
            "summary": "",
            "url": "classes/Core-Router.html#method_toCamelCase"
        },                {
            "fqsen": "\\Core\\Router\u003A\u003AgetNamespace\u0028\u0029",
            "name": "getNamespace",
            "summary": "",
            "url": "classes/Core-Router.html#method_getNamespace"
        },                {
            "fqsen": "\\Core\\Router\u003A\u003ApreviousUrl\u0028\u0029",
            "name": "previousUrl",
            "summary": "",
            "url": "classes/Core-Router.html#method_previousUrl"
        },                {
            "fqsen": "\\Core\\Router\u003A\u003A\u0024routes",
            "name": "routes",
            "summary": "",
            "url": "classes/Core-Router.html#property_routes"
        },                {
            "fqsen": "\\Core\\Router\u003A\u003A\u0024params",
            "name": "params",
            "summary": "",
            "url": "classes/Core-Router.html#property_params"
        },                {
            "fqsen": "\\Core\\Router\u003A\u003A\u0024request",
            "name": "request",
            "summary": "",
            "url": "classes/Core-Router.html#property_request"
        },                {
            "fqsen": "\\Core\\Router\u003A\u003A\u0024response",
            "name": "response",
            "summary": "",
            "url": "classes/Core-Router.html#property_response"
        },                {
            "fqsen": "\\Core\\View",
            "name": "View",
            "summary": "",
            "url": "classes/Core-View.html"
        },                {
            "fqsen": "\\Core\\View\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Core-View.html#method___construct"
        },                {
            "fqsen": "\\Core\\View\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "",
            "url": "classes/Core-View.html#method_render"
        },                {
            "fqsen": "\\Core\\View\u003A\u003A\u0024viewPath",
            "name": "viewPath",
            "summary": "",
            "url": "classes/Core-View.html#property_viewPath"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Core",
            "name": "Core",
            "summary": "",
            "url": "namespaces/core.html"
        }            ]
);
